---
- name: Creates directory
  file:
    path: ~/web
    state: directory
- unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/web"
- name: Executing node
  shell: |
    cd ~/web/dist
    npm install
    pm2 stop default
    pm2 start main.js -- start

